# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9019db0be3ef0254a49fed8bdab765013501edcedff7df781887a81144fdda8fe47d22f154e3d965cee5208707ac90954d480c6aedd1c328dd85b44b2fe34826

test:
  secret_key_base: 31b81e5acb3a6aab78a632150cd53f39367946a475c8fa54d949d6c7e87fb93d9dcf86d4889068d72c1ded14f1ec7c173eb374c428b46a6908b70381102a3944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
